### ISSUE TITLE
memcache_server does not work in Dalli

### ISSUE THREAD

**Issue by vincenting** [sinatra/sinatra-recipes#108]
http://recipes.sinatrarb.com/p/middleware/share_session_with_memcached 

`memcache_server: 'example.com:11211'` does not make sense in the latest version.
 use `cache: Dalli::Client.new('example.com:11211')` instead.

**Comment by kgrz** [comment]
Ah, thanks for noticing this. What you mentioned is true. Will you open a PR? Or else I'll try to do something over weekend

**Comment by vincenting** [comment]
https://github.com/sinatra/sinatra-recipes/pull/109
