### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra-recipes#44]
The following are recipes wanted for the sinatra cookbook, feel free to add any to the list that you'd like to see:

- [x] [glorify](https://github.com/zzak/glorify)
- [x] [sinatra-assetpack](https://github.com/rstacruz/sinatra-assetpack)
- [x] [omniauth](https://github.com/intridea/omniauth)
- [x] [Rack::Reloader](https://github.com/rack/rack)
- [ ] ...

**Comment by nzwsch** [comment]
@zzak How about adding `Security` which recipes about protecting apps?
